# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "nfra/kickstart-flavor-php:7.4"

packages: wget

command:
  build:
    - "composer update"
  init:
  test:
    - "vendor/bin/phpunit --bootstrap vendor/autoload.php --testdox test"
  run:

  mkdoc:
    - wget --mirror --convert-links --html-extension --directory-prefix=/opt/docs http://localhost
  dev:
    - "echo 'I am executed in dev mode'"
